[project]
name = "ilovenotes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "librosa>=0.10.2.post1",
    "llvmlite>=0.43.0",
    "numba>=0.60.0",
    "numpy>=2.0.2",
    "soundfile>=0.12.1",
]
